In [1]:
#import depedencies
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import os
from sqlalchemy import create_engine

In [2]:
# Get data from csv
football_df = pd.read_csv("Resources/Football Players Stats (Premier League 2021-2022).csv", encoding="ISO-8859-1")
football_df.head(-5)

,Player,Team,Nation,Pos,Age,MP,Starts,Min,90s,Gls,...,G+A-PK,xG,npxG,xA,npxG+xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA.1
0,Bukayo Saka,Arsenal,eng ENG,"FW,MF",19.0,38,36,"2,978",33.1,11.0,...,0.48,9.7,8.2,6.9,15.2,0.29,0.21,0.50,0.25,0.46
1,Gabriel Dos Santos,Arsenal,br BRA,DF,23.0,35,35,"3,063",34.0,5.0,...,0.15,2.7,2.7,0.8,3.5,0.08,0.02,0.10,0.08,0.10
2,Aaron Ramsdale,Arsenal,eng ENG,GK,23.0,34,34,"3,060",34.0,0.0,...,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
3,Ben White,Arsenal,eng ENG,DF,23.0,32,32,"2,880",32.0,0.0,...,0.00,1.0,1.0,0.6,1.6,0.03,0.02,0.05,0.03,0.05
4,Martin Ødegaard,Arsenal,no NOR,MF,22.0,36,32,"2,785",30.9,7.0,...,0.36,4.8,4.8,6.8,11.6,0.16,0.22,0.38,0.16,0.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
681,Chem Campbell,Wolverhampton Wanderers,wls WAL,MF,18.0,1,0,13,0.1,0.0,...,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
682,Morgan Gibbs-White,Wolverhampton Wanderers,eng ENG,"FW,MF",21.0,2,0,9,0.1,0.0,...,0.00,0.1,0.1,0.0,0.1,1.22,0.00,1.22,1.22,1.22
683,Hugo Bueno,Wolverhampton Wanderers,es ESP,DF,18.0,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
684,Ryan John Giles,Wolverhampton Wanderers,eng ENG,MF,21.0,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
685,Bruno Jordão,Wolverhampton Wanderers,pt POR,MF,22.0,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#total no of players
total_players=len(football_df["Player"].unique())
total_players

678

In [4]:
#total no of teams:
total_team=len(football_df["Team"].unique())
total_team

20

In [5]:
#total match played
#total goals
#calculate overall percentage of expected goals (mean)
match_played= football_df["MP"].sum()
print(f"Total match played: {match_played}")
match_goals= football_df["Gls"].sum()
print(f"Total goals played: {match_goals}")
print(f"Expected goals when played: {football_df['Gls'].mean()*100:.2f}%")

Total match played: 10485
Total goals played: 1037.0
Expected goals when played: 189.58%

In [6]:
#players positions
football_df.groupby("Pos").size().sort_values()

Pos
FW,DF      2
DF,FW      4
DF,MF      9
MF,DF     11
MF,FW     39
FW,MF     62
GK        74
FW        99
MF       158
DF       233
dtype: int64

In [7]:
#players in team Arsenal
football_df_Arsenal= football_df[football_df["Team"]=="Arsenal"].copy()
football_df_Arsenal.head(5)

,Player,Team,Nation,Pos,Age,MP,Starts,Min,90s,Gls,...,G+A-PK,xG,npxG,xA,npxG+xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA.1
0,Bukayo Saka,Arsenal,eng ENG,"FW,MF",19.0,38,36,"2,978",33.1,11.0,...,0.48,9.7,8.2,6.9,15.2,0.29,0.21,0.50,0.25,0.46
1,Gabriel Dos Santos,Arsenal,br BRA,DF,23.0,35,35,"3,063",34.0,5.0,...,0.15,2.7,2.7,0.8,3.5,0.08,0.02,0.10,0.08,0.10
2,Aaron Ramsdale,Arsenal,eng ENG,GK,23.0,34,34,"3,060",34.0,0.0,...,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
3,Ben White,Arsenal,eng ENG,DF,23.0,32,32,"2,880",32.0,0.0,...,0.00,1.0,1.0,0.6,1.6,0.03,0.02,0.05,0.03,0.05
4,Martin Ødegaard,Arsenal,no NOR,MF,22.0,36,32,"2,785",30.9,7.0,...,0.36,4.8,4.8,6.8,11.6,0.16,0.22,0.38,0.16,0.38

In [8]:
#calculate overall percentage of players goals in Arsenal
football_df["Arsenal"]= football_df["Gls"]>=5
percent_Arsenal_goal =((football_df["Arsenal"]).mean())*100
percent_Arsenal_goal

11.143270622286542